FROM public.ecr.aws/lambda/python:3.12

COPY src/lambda/requirements.txt ${LAMBDA_TASK_ROOT}/requirements.txt
RUN pip install --no-cache-dir -r ${LAMBDA_TASK_ROOT}/requirements.txt

COPY src ${LAMBDA_TASK_ROOT}/src

CMD ["src.lambda.lambda_handler.handler"]